### ISSUE TITLE
double digit groups not recognized

### ISSUE THREAD

**Issue by aguyinmontreal** [javallone/regexper-static#43] opened 2017-09-13 22:27 UTC
`(1)(2)(3)(4)(5)(6)(7)(8)(9)(10)\10`

Doesn't recognize double digit groups such as `10`

![image](https://user-images.githubusercontent.com/19701656/30571837-4aea9b5a-9cb8-11e7-86bb-97a928f6c352.png)

**Comment by xgqfrms-gildata** [comment] 2017-09-19 00:56
![image](https://user-images.githubusercontent.com/29531779/30571142-504ed20e-9d18-11e7-851c-01dd03c1ed07.png)

more info needed!

**Comment by xgqfrms-gildata** [comment] 2017-09-19 01:06
# Maybe you should learn regex in deepth!

https://regexper.com/#%2F(12)%2F

![image](https://user-images.githubusercontent.com/29531779/30571324-8995d75a-9d19-11e7-8cc2-a2c13ad7c093.png)

![image](https://user-images.githubusercontent.com/29531779/30571356-b4bf2030-9d19-11e7-8abf-7f1330ed9451.png)

https://regexper.com/#%2F(1)(2)(3)(4)(5)(6)(7)(8)(9)(10)((%3F%3D(%5B0-9%5D%7B1%2C6%7D)))(12)%2F

**Comment by aguyinmontreal** [comment] 2017-09-19 01:24
euuh... I think your talking about the litteral "12".

I'm talking about the back-reference to capturing group 12 (which is this part: `([0-9]{1,6})`).

see regex101.com : 
![image](https://user-images.githubusercontent.com/19701656/30571742-b69b6a2e-9cb7-11e7-9190-d41d167f57da.png)

**Comment by xgqfrms-gildata** [comment] 2017-09-22 08:11
I don't know what your means?

You should give more details & some handy ways!

# bad way
`see regex101.com :`

# good way

see: https://regex101.com/

```code

(1)(2)(3)(4)(5)(6)(7)(8)(9)(10)((?=([0-9]{1,6})))(12)

```

**Comment by aguyinmontreal** [comment] 2017-09-22 12:54
Please look at the first post, I edited it.

**Comment by javallone** [comment] 2018-02-10 17:15
Closing as a duplicate of #38.

**Closed by javallone** 2018-02-10 17:15 UTC
