### ISSUE TITLE
slightly confusing visual of the "repeat" regex function

### ISSUE THREAD

**Issue by pokeball99** [javallone/regexper-static#27] opened 2016-03-29 13:32 UTC
(([b-df-hj-np-tv-xz][aeiou]){5})|(([B-DF-HJ-NP-TV-XZ][AEIOU]){5})
says repeat 4 times, while i understand why it is shown that way, it does make it slightly confusing

**Comment by ThibWeb** [comment] 2016-06-26 20:51
Hey @pokeball99, I think this is the same issue as https://github.com/javallone/regexper-static/issues/14.

**Comment by javallone** [comment] 2016-07-26 22:09
Closing as duplicate of #14

**Closed by javallone** 2016-07-26 22:09 UTC
