### ISSUE TITLE
items {n,m}

### ISSUE THREAD

**Issue by Viky-zhang** [javallone/regexper-static#19] opened 2015-11-19 07:44 UTC
my regex str:
[0-9A-Za-z]{2,4}

![image](https://cloud.githubusercontent.com/assets/2208880/11265090/4e9cd036-8ed4-11e5-82c5-337a1f5e071c.png)

why {2,4} not means 2-4 items?

**Comment by Byron** [comment] 2016-01-03 16:58
This seems to be a duplicate of #14.

**Comment by holloway** [comment] 2016-01-28 02:33
This regex is still http://regexper.com/#%5Cn%7B1%2C2%7D being reported as "at most once".

**Comment by ThibWeb** [comment] 2016-06-26 20:52
What is labeled "at most once" is _the loop_, not the overall expression. Clear duplicate of https://github.com/javallone/regexper-static/issues/14.

**Comment by javallone** [comment] 2016-07-26 22:10
Closing as duplicate of #14

**Closed by javallone** 2016-07-26 22:10 UTC
